### ISSUE TITLE
Undefined column error on postgres

### ISSUE THREAD

**Issue by ul8** [lindseydiloreto/craft-inventory#11]
When accessing the plugin main page on a Craft 3 site using postgres I'm getting the error below.

I could fix the issue by enclosing the column names in double quotes, e. g. in src/services/InventoryService.php
`->where('fieldId=:id', [':id' => $field->id])`
becomes
`->where('"fieldId"=:id', [':id' => $field->id])`

With the same change also applied to "fieldLayoutId", the plugin index page works fine.

I don't have much experience in postgres so I'm not sure if I'm missing anything here, but this might be useful to someone.

```SQLSTATE[42703]: Undefined column: 7 ERROR: column "fieldid" does not exist
LINE 3: WHERE fieldId=$1
^
HINT: Perhaps you meant to reference the column "craft_fieldlayoutfields.fieldId".
The SQL being executed was: SELECT "layoutId", "tabId"
FROM "craft_fieldlayoutfields"
WHERE fieldId=554
ORDER BY "layoutId"
Error Info: Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  column "fieldid" does not exist
LINE 3: WHERE fieldId=$1
              ^
HINT:  Perhaps you meant to reference the column "craft_fieldlayoutfields.fieldId".
)
↵
Caused by: PDOException
SQLSTATE[42703]: Undefined column: 7 ERROR: column "fieldid" does not exist
LINE 3: WHERE fieldId=$1
^
HINT: Perhaps you meant to reference the column "craft_fieldlayoutfields.fieldId".

**Comment by lindseydiloreto** [comment]
Thanks for reporting! I had failed to properly quote the column names per [Yii2 recommendations](https://www.yiiframework.com/doc/guide/2.0/en/db-dao#quoting-table-and-column-names).

I've just released **v2.0.3**, which patches this bug. 👍
