### ISSUE TITLE
Inventory showing count for entry types of sections that have been removed

### ISSUE THREAD

**Issue by ryanmasuga** [lindseydiloreto/craft-inventory#12]
I'm in the process of cleaning up a site and I've removed some old sections. When I go into Inventory, I see that it's still showing some fields attached to entry types for those sections that no longer exist. Am I missing a step in cleaning out those entry types, or is Inventory caching results?

A more accurate count for the `callToActionText` field would be 6, not 12!

Sample of first few rows of what I see for that field: 
![image](https://user-images.githubusercontent.com/988995/67107765-11100c00-f19b-11e9-9329-9a954fc4765b.png)

**Comment by ryanmasuga** [comment]
Could this have anything to do with soft deletion?

**Comment by ryanmasuga** [comment]
I think it does. The sections and related layouts are still in the DB and the `dateDeleted` fields are populated. Perhaps Inventory could be modified to not show soft deleted sections.

**Comment by lindseydiloreto** [comment]
Very interesting, good catch! Thanks for digging deep enough to figure out that soft deletions were the cause of the problem.

I'll make some adjustments so that Inventory ignores soft deleted sections.

**Comment by furioursus** [comment]
Yeah, this is definitely something that would help with us in some of our site sections at Oakland, too! Sometimes general content entry types “graduate” to a new section and we end up having to delete their previous home.

**Comment by ryanmasuga** [comment]
Ran into this again today in Craft 3.4.8. Trying to clean up a site, and Inventory is showing 14 uses of a field - but I would expect it to be 0, because every one of those sections has been deleted, and I suppose they're currently sitting in the soft deleted state.

**Comment by lindseydiloreto** [comment]
Just gave Inventory a nice UI makeover in accordance with Craft 3.4, and made sure this feature request made it into the mix...

<img width="739" alt="Ω 2020-04-10 at 7 41 25 AM" src="https://user-images.githubusercontent.com/5309692/78999227-0eb1bd80-7aff-11ea-80f6-00e87e0422ac.png">

This is now available in **v2.1.0**! 🎉
