### ISSUE TITLE
'Call to undefined method' on Vizy Field

### ISSUE THREAD

**Issue by kerns** [lindseydiloreto/craft-inventory#14]
Not sure if this one is on you or @engram-design but Vizy and Inventory are not yet friends. 🤷🏻‍♂️Not even on speaking terms. Not serious but thought you should know.

**Comment by engram-design** [comment]
This is a my issue thing - fixed in https://github.com/verbb/vizy/commit/d61f940a361f7a5387a6ab625f7faacca13f736f

**Comment by lindseydiloreto** [comment]
Excellent, thanks @engram-design! 🍺

**Comment by Crawf** [comment]
Really no idea what you are talking about.  I think you have the wrong
person.

**Comment by lindseydiloreto** [comment]
@Crawf "crawf" is the Discord screen name for @engram-design. Sorry for the confusion.
