### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by aanimation** [lindseydiloreto/craft-inventory#18]
Hi, im using craft-inventory to check fields, but actually after install on craft 4.3.10
i got this, pls help

Trying to access array offset on value of type null

 in /var/www/html/vendor/doublesecretagency/craft-inventory/src/services/InventoryService.php line 179

**Comment by lindseydiloreto** [comment]
Hi @aanimation, sorry for the late response.

Do you have any other information regarding this error? Can you still reproduce the issue?

If you can, please take a screenshot of the full stack trace.

**Comment by lindseydiloreto** [comment]
This sounds a lot like #16... Unfortunately, I'm having trouble reproducing it.

@aanimation Would you be willing to provide a copy of your database? I suspect this only happens to sites which have been updated from an older version of Craft.

**Comment by MattWilcox** [comment]
I've just installed this on a new project and instantly hit the error. Not an updated Craft. I can throw a DB your way if it helps.

<img width="1280" alt="Screenshot 2023-04-21 at 15 47 21" src="https://user-images.githubusercontent.com/814039/233666245-6956dea7-97ea-4439-93ad-03e294073dda.png">

**Comment by lindseydiloreto** [comment]
That sounds great @MattWilcox, thanks! I'll ping you on Discord 👍

**Comment by lindseydiloreto** [comment]
Great news, this is fixed in [v3.0.0](https://github.com/doublesecretagency/craft-inventory/releases/tag/3.0.0)! 🎉 

Thanks for lending me your database @MattWilcox, it made a huge difference. 🙏

**Comment by anita-chouhan** [comment]
Hello, I am also getting the same error for _craft-inventory_ plugin on Craft CMS version 4.5.9

<img width="915" alt="Screenshot 2023-11-09 at 3 16 49 PM" src="https://github.com/doublesecretagency/craft-inventory/assets/30666052/25faab8e-9fb2-4599-90fd-1b6736f134fc">

**Additional Info**
Craft CMS version: 4.5.9
Field Inventory version: 3.1.1
PHP version: 8.0.15

**Comment by anita-chouhan** [comment]
Hello @lindseydiloreto, any updates on the reported issue?

**Comment by lindseydiloreto** [comment]
Hi @anita-chouhan,

Despite the similar error message, this seems unrelated to the original post.

Would you mind sharing a copy of your database with me? That would make it much easier for me to track down the problem.

Feel free to DM me on Discord, where you can send me the files needed to reproduce the issue.
