### ISSUE TITLE
"This field is translatable" column

### ISSUE THREAD

**Issue by carlcs** [lindseydiloreto/craft-inventory#2]
I'd love to see a column that indicated whether that setting is enabled or not. We currently have to open every field type individually to get that info.

**Comment by lindseydiloreto** [comment]
That's pretty interesting!

I'll put some thought into it, but that sounds like a reasonable FR. I'll leave this thread open until I (eventually) get around to adding it.

**Comment by lindseydiloreto** [comment]
Good news... I stumbled across an easy way to do this while converting it to Craft 3.

This will be included in the next release.  👍
