### ISSUE TITLE
Impossible to access Utilities > Field Inventory after update from 2.2 to 3.0.1

### ISSUE THREAD

**Issue by MattWilcox** [lindseydiloreto/craft-inventory#21]
Just run the update, and now all I'm getting it the following:

<img width="1280" alt="Screenshot 2023-04-26 at 17 11 27" src="https://user-images.githubusercontent.com/814039/234636856-47ae3f59-c3a5-4d71-ace9-f59acd5e8437.png">

**Comment by lindseydiloreto** [comment]
Ah, that was a late addition to support multi-site projects. Accidentally broke it for single-site projects though. 😅 

Will be pushing a fix shortly, thanks for reporting!

**Comment by lindseydiloreto** [comment]
This is now fixed in [v3.0.2](https://github.com/doublesecretagency/craft-inventory/releases/tag/3.0.2). Thanks again for reporting it! 🍺
