### ISSUE TITLE
Option to disable the plugin in non-`dev` environments

### ISSUE THREAD

**Issue by estebancastro** [lindseydiloreto/craft-inventory#22]
Option for active use of the plugin only on **development** mode? I think most of the time it is not necessary to see this plugin on production.

You know... on production Craft Settings are not visible, fields are not visible, it is not necessary to see the fields on production, same for this plugin, this useful plugin is best to work locally on dev mode.

Just a silly example, but you have the idea, config/inventory.php

```
$isDev = App::env('ENVIRONMENT') === 'dev';

return [
    '*' => [
        'inventoryEnabled' => $isDev,
```

**Comment by lindseydiloreto** [comment]
Good news, this is already possible using Craft's native [`disabledPlugins`](https://craftcms.com/docs/4.x/config/general.html#disabledplugins) setting!

```php
// Global settings
'*' => [
    ...
],
// Dev environment settings
'dev' => [
    'disabledPlugins' => ['inventory']
]
```

Or alternatively...

```php
// All settings together, but dynamic
'*' => [
    'disabledPlugins' => [
        (App::env('ENVIRONMENT') === 'dev' ? 'inventory' : null)
    ]
]
```

I disagree that Inventory should always be hidden in non-`dev` environments. There are valid reasons for wanting to see where fields are being used, even while navigating a `production` site.

It's true, however, that those fields aren't editable if `allowAdminChanges` is disabled. So I've just [pushed a fix](https://github.com/doublesecretagency/craft-inventory/releases/tag/3.1.1) which hides the "edit" buttons and clarifies when Inventory is in "read only" mode...

<img width="850" alt="[Read Only]  Field changes are not permitted in this environment." src="https://github.com/doublesecretagency/craft-inventory/assets/5309692/77076aa5-e77a-476f-b7c6-a0c79063ebff">


Hope that helps! 🙂
