### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by maxwellhibbert** [lindseydiloreto/craft-inventory#3]
Trying to get property of non-object
inventory/services/InventoryService.php(66)

That's what I get when trying to access the plugin..

**Comment by lindseydiloreto** [comment]
Haven't seen that before... what exactly were you doing when that popped up?

What are the steps I should take to reproduce it?

**Comment by maxwellhibbert** [comment]
I installed the plugin, then clicked the "Inventory" link in the sidebar.
Using Craft 2.6.2967, PHP 7

**Comment by lindseydiloreto** [comment]
Strange. Is there a stack trace you could share here?

**Comment by maxwellhibbert** [comment]
Sure
![screen_10](https://cloud.githubusercontent.com/assets/2948524/23817066/818bfd4e-0644-11e7-9d8b-64611f5ae9d0.png)

**Comment by lindseydiloreto** [comment]
Hmm, that helps a little... looks like something might be screwy with your database.

Are you on Craft Slack? If so, would you mind pinging me @lindseydiloreto.

If you're not on Craft Slack, shoot me an email at support@doublesecretagency.com.

We're probably dealing with an edge case here, but I'll try to adjust the plugin to be more defensive. Hit me up so we can troubleshoot in greater detail.

**Comment by maxwellhibbert** [comment]
I'm not sure how, but the plugin is now working. Sorry to have taken up your time. If I ever work out what the problem was, I'll let you know.

**Comment by lindseydiloreto** [comment]
Sounds good, thanks for the update!

**Comment by tobystokes** [comment]
I'm getting the exact same error / stack trace as above.
(and i'm on craft slack with the same username as here, if you're interested in fixing!)

**Comment by lindseydiloreto** [comment]
Hey @tobystokes sorry for the delayed response...

I am definitely interested in fixing it, although it'll have to wait for the Craft 3 version. My goal is to have it ready within the next few weeks.

Who knows... maybe the very act of porting it to Craft 3 will fix the problem! :)

**Comment by lindseydiloreto** [comment]
Alright, this has been officially ported to Craft 3. 👍 

If anyone else runs into this issue on Craft 3, please let me know!
