### ISSUE TITLE
Add ability to delete field

### ISSUE THREAD

**Issue by tjdraper** [lindseydiloreto/craft-inventory#4]
Per our conversation on Slack, it would be great to have the ability to delete fields that aren't in use right from the inventory screen. 👍

**Comment by lindseydiloreto** [comment]
Good suggestion, thanks! I'll circle back on this at some point in the future. 👍

**Comment by lindseydiloreto** [comment]
With the release of **v2.1.0**, it is now possible to delete unused fields from the Inventory UI! 🎉

<img width="741" alt="button to delete unused field" src="https://user-images.githubusercontent.com/5309692/78998906-6e5b9900-7afe-11ea-9e0f-585c92bfd4e2.png">
