### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by molwells** [lindseydiloreto/craft-inventory#6]
I'd like to use Inventory on a client project, but the client is hesitant because the plugin has no licensing info. Would it be possible to add a license to your project?

**Comment by lindseydiloreto** [comment]
Hi @molwells,

The license is actually nested one folder down, contained within the installable `/inventory` directory.

https://github.com/lindseydiloreto/craft-inventory/blob/master/inventory/LICENSE.txt

Hope that helps, let me know if you have additional questions!
