### ISSUE TITLE
Make Available via `composer` Compatible with Craft 2

### ISSUE THREAD

**Issue by wesleyboar-fka-iosulfur** [lindseydiloreto/craft-inventory#7]
**Summary**

Some companies still require Craft 2. The last Craft 2-compatible commit is desirable. But, that commit is not available as a release in a way that is readily available via `composer`.

**Steps**

Unsuccessful Installation of 1.0.1

1. `composer require --dev doublesecretagency/craft-inventory:1.0.1`

        [InvalidArgumentException]                                                             
        Could not find package doublesecretagency/craft-inventory in a version matching 1.0.1

2. `composer require --dev doublesecretagency/craft-inventory`

        Your requirements could not be resolved to an installable set of packages.

          Problem 1
            - craftcms/cms 3.0.0-RC8 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
            - craftcms/cms 3.0.0-RC7.1 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
            - craftcms/cms 3.0.0-RC7 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
            - craftcms/cms 3.0.0-RC6 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
            - craftcms/cms 3.0.0-RC5 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
            - craftcms/cms 3.0.0-RC4 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
            - craftcms/cms 3.0.0-RC3 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
            - craftcms/cms 3.0.0-RC2 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
            - craftcms/cms 3.0.0-RC1 requires php >=7.0.0 -> your PHP version (5.4.16) does not satisfy that requirement.
            - doublesecretagency/craft-inventory 2.0.0 requires craftcms/cms ^3.0.0-RC1 -> satisfiable by craftcms/cms[3.0.0-RC1, 3.0.0-RC2, 3.0.0-RC3, 3.0.0-RC4, 3.0.0-RC5, 3.0.0-RC6, 3.0.0-RC7, 3.0.0-RC7.1, 3.0.0-RC8].
            - Installation request for doublesecretagency/craft-inventory -> satisfiable by doublesecretagency/craft-inventory[2.0.0].

        Installation failed, reverting ./composer.json to its original content.

Successful Installation of 1.0.1

1. Download [zip file at specific commit just before the one tagged `2.0.0`](https://github.com/doublesecretagency/craft-inventory/archive/44d404f91e3ba2498ec01f6095783f47bbe318e3.zip).
2. Unzip file.
3. Move `inventory` directory from unzipped contents to `craft/plugins/inventory`.
4. Open Craft CMS admin interface to "Plugins" settings page.
5. Install plugin.

**Comment by lindseydiloreto** [comment]
Sorry, we won't be making the Craft 2 version compatible with Composer for several reasons.

We have about a dozen plugins. For consistency sake, we'd need to make _all_ of them compatible with Composer if we converted this one. Unfortunately, we simply don't have the time or resources to convert all Craft 2 versions of our plugins to be Composer compatible. Our energy is currently focused on making sure that all plugins have been properly ported to Craft 3... which includes Composer compatibility for all Craft 3 plugins.

We are excited that our Craft 3 versions are all Composer compatible!

**For Craft 3**, install the `v2` branch via Composer or the plugin store.

**For Craft 2**, install the `v1` branch as you described in your successful installation steps.
