### ISSUE TITLE
Calendar Event Not Found

### ISSUE THREAD

**Issue by worshiplive** [lindseydiloreto/craft-inventory#8]
Getting this error after install and I go to click on to see inventory.

Class 'Calendar_Event' not found

**Comment by lindseydiloreto** [comment]
Hmm, sounds like something specific to your database. `Calendar_Event` doesn't appear in this plugin's code.

Is this for Craft 2 or Craft 3? Ping me on [Craft Slack](https://craftcms.com/community#slack) (@lindseydiloreto), I may need to see your database.

**Comment by lindseydiloreto** [comment]
I've improved the way Inventory handles missing element types. This is now fixed in **2.0.1**.

**Comment by worshiplive** [comment]
Perfect! Thanks Lindsey, above and beyond.
